import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../src/components/Header'
import styles from '../styles/Home.module.css'
import fundo from '../src/images/fundoInicial.png'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>GoBook</title>
        <meta name="description" content="Book recommendation App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.index}>
        <Image src={fundo} 
        className={styles.ilustration}
        width={700}
        height={655}/>

        <div className={styles.interact}>
          <h1 className={styles.title}>
          VAMOS DESCOBRIR UM NOVO LIVRO?
          </h1>

          <p className={styles.description}>
          Oi, eu sou a Bibi, sua parceira de leitura, vou te ajudar a descobrir qual é o livro ideal para você aproveitar uma boa leitura.
          <br/>
          <br/>
          Nesse quiz, nós iremos explorar seu gosto pessoal e lhe contar um pouco sobre nossa história do Conselho Comunitário dos Moradores do Parque Santa Cecília.
          </p>

          <div className={styles.action}>
            <button className={styles.bigButton}>
              <Link href="/questions">
                <a>COMEÇAR</a>
              </Link>
            </button>
          </div>
        </div>
      </main>

    </div>

    /*<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    */
  )
}
